import { dataTypes } from "./data-types.js";
import { letVar } from "./let-var.js";
import { prototype } from "./prototype.js";
import { objects } from "./objects.js";
import { hoisting } from "./hoisting.js";
import { functions } from "./functions.js";
import { closure } from "./closure.js";
import { typeConversion } from "./type-conversion.js";
import { expressionsOperators } from "./expr-oper.js";
import { controlFlow } from "./control-flow.js";

// dataTypes();
// letVar();
// prototype();
// objects();
// hoisting();
// functions();
// closure();
typeConversion();
// expressionsOperators();
// controlFlow();
